### ISSUE TITLE
Ground Truth Labels for 4D Volume Formation during Training

### ISSUE THREAD

**Issue by LarsKreuzberg** [MehmetAygun/4D-PLS#8]
Hi @MehmetAygun!
Many thanks for sharing your code. It is a really interesting work!

I have a question about the 4D Volume Formation during training. At this [point](https://github.com/MehmetAygun/4D-PLS/blob/b8963d4ac2bc65acbb42691cb1cec7c89a012f9d/datasets/SemanticKitti.py#L365) you use the **ground truth** center and semantic labels to find out which points of the previous frames belong to thing classes and which are close to object center, right?
During testing/validation, on the other hand, you use the **predictions** of the previous frames for the 4D volume formation ([here](https://github.com/MehmetAygun/4D-PLS/blob/b8963d4ac2bc65acbb42691cb1cec7c89a012f9d/datasets/SemanticKitti.py#L380)). 
This allows you to use multi-thread data-loaders during training, but not during testing/validation. Do I understand this correctly?
Based on your description of 4D Volume Formation in the paper, I would have thought that we would also use the **predicted** labels and not the **GT** labels of the previous frames during training for the 4D Volume Formation. The problem here would be that the training would take much longer, right?

Thank you very much for your help!

**Comment by MehmetAygun** [comment]
Hi @LarsKreuzberg ,

Thanks for your interest. Yeah, exactly as you described I am using gt values during training and predictions for val/test. 

As you said, if you want to use predictions for training, you need to wait until the previous frame is processed. Also, you had to train your network using only consecutive frames, which might also affect the training performance since you will not get diverse examples. 

Hope it will help, otherwise, I am glad to explain further if some parts are not clear!
